name: build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-corss:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
            output: bore
          - target: aarch64-linux-android
            output: bore
    steps:
      - uses: actions/checkout@v2
      - run: echo '[build]' > Cross.toml && echo 'build-std = true' >> Cross.toml
        if: contains(matrix.target, 'android')
      - name: install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: ${{ matrix.target }}
          override: true
      - name: compile
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=${{ matrix.target }}
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: bore-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/${{ matrix.output }}

